server:
  port: 9191

spring:
  application:
    name: API-GATEWAY

cloud:
    gateway:
      routes:
        - id: ADMIN-SERVICE
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/user/**
        
        - id: LOGIN-SERVICE
          uri: lb://LOGIN-SERVICE
          predicates:
            - Path=/login/**
         





eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        hostname: localhost
       