server:
  port: 9191
spring:
    application:
        name: API-GATEWAY
    cloud:
        gateway:
            default-filters:
              - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            globalcors:
              corsConfigurations:
                '[/**]':
                    allowedOrigins: "*"
                    allowedMethods: "*"
                    allowedHeaders: "*"
            
            routes:
                - id: LOGIN-SERVICE
                  uri: http://localhost:9001/login/
                  predicates:
                  - Path=/login/**
                - id: ADMIN-SERVICE
                  uri: http://localhost:9002/user/
                  predicates:
                  - Path=/user/**  

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        hostname: localhost
       